### ISSUE TITLE
[Bug] Exception during update loop

### ISSUE THREAD

**Issue by eingruenesbeb** [jenchanws/create-track-map#28]
Hello 👋🏻
I'd like to report an issue, that causes the map to be unable to update and which is also spamming the logs.

Here are some few details:
- Server version: Minecraft 1.19.2 with Fabric Loader 0.14.19
- [Modlist](https://gist.github.com/eingruenesbeb/ffaad6210186043f23b122597fb1d3dc) (Create Live 4 Modpack + additional mods)

Steps to reproduce:
I unfortunately do not know the steps to reproduce this issue, but I'll download the world for testing purposes and post it as a comment tomorrow morning. (the map is quite big)

Here is the error message in detail:
```
[22:13:09] [TrackMap watcher/WARN]: Exception during update loop
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.simibubi.create.content.logistics.trains.TrackEdge.getLength()" because "this.edge" is null
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at com.simibubi.create.content.logistics.trains.entity.TravellingPoint.getPositionWithOffset(TravellingPoint.java:402)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at com.simibubi.create.content.logistics.trains.entity.TravellingPoint.getPosition(TravellingPoint.java:398)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at littlechasiu.ctm.ExtensionsKt.getSendable(Extensions.kt:60)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at littlechasiu.ctm.ExtensionsKt.getSendable(Extensions.kt:67)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at littlechasiu.ctm.ExtensionsKt.getSendable(Extensions.kt:83)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at littlechasiu.ctm.TrackWatcher.getTrainStatus(TrackWatcher.kt:226)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at littlechasiu.ctm.TrackWatcher.update(TrackWatcher.kt:343)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at littlechasiu.ctm.TrackWatcher.watch(TrackWatcher.kt:61)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at littlechasiu.ctm.TrackWatcher.access$watch(TrackWatcher.kt:24)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at littlechasiu.ctm.TrackWatcher$start$1$1$1.invokeSuspend(TrackWatcher.kt:42)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at littlechasiu.ctm.TrackWatcher$start$1.invoke(TrackWatcher.kt:40)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at littlechasiu.ctm.TrackWatcher$start$1.invoke(TrackWatcher.kt:39)
[22:13:09] [TrackMap watcher/INFO]: [STDERR]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

```

Thanks for your time developing this awesome mod. I hope that this bug report helps making it even better.
~ Beb

**Comment by eingruenesbeb** [comment]
Here's the world download for testing purposes: https://www.mediafire.com/file/4c2rj575lsf981y/world.zip/file
