### ISSUE TITLE
Mod won't launch

### ISSUE THREAD

**Issue by german2285** [jenchanws/create-track-map#57]
### Describe the Bug

In general, I'm renting a server for Minecraft to play with friends. I only installed 3 mods and it gave me this error, if anything I’m using the latest Mohist kernel.

### Reproduction Steps

1. Downloaded the kernel
2. installed the kernel
3. Installed for pirates
4. Install 3 mods
5. Started the server
Note: I wanted to open a different port because the host does not allow me to open a certain port.

### Expected Result

Exception in thread "main" java.lang.module.ResolutionException: Modules createtrackmap and org.fusesource.jansi export package org.fusesource.jansi.internal to module thedarkcolour.kotlinforforge.lib
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:104)

### Operating System

I don't know

### CTM Version

1.4

### Create Version

0.5.1d

### Minecraft Version

1.20.1

### Mod Loader

Other

### Modloader Version

498

### Instance Type

Shared hosting provider

### Other Mods

create-1.20.1-0.5.1.d.jar
create-track-map-1.4+mc1.20.1-neoforge (1).jar
kotlinforforge-4.7.0-all.jar

**Comment by german2285** [comment]
Thanks for using Mohist - 1.20.1-528, Java(19.0.2) 63.0
Update in check...
If you don't want to enable update check, set check_update in mohist-config/mohist.yml to false
No update found, latest version: (1.20.1-528) current version: (1.20.1-528)
Checking libraries, please wait...
All libraries are nice :)!
Searching incompatible mods...
[16:13:36 INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.16, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, nogui]
[16:13:36 INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 19.0.2 by Eclipse Adoptium; OS Linux arch amd64 version 5.15.0-83-generic
[16:13:36 INFO]: ImmediateWindowProvider not loading because launch target is forgeserver
[16:13:36 INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/container/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23111!/ Service=ModLauncher Env=SERVER
[16:13:36 INFO]: Found 5 dependencies adding them to mods collection
Exception in thread "main" java.lang.module.ResolutionException: Modules createtrackmap and org.fusesource.jansi export package org.fusesource.jansi.internal to module flywheel
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:104)

**Comment by enbyv** [comment]
> Thanks for using Mohist - 1.20.1-528, Java(19.0.2) 63.0

Well, there's your problem.

[PSA: Do not use Mohist](https://essentialsx.net/do-not-use-mohist.html)
