### ISSUE TITLE
so i got this error wen trying to get in to the world

### ISSUE THREAD

**Issue by Omoli822** [jenchanws/create-track-map#79]
### Describe the Bug

my crash report is ---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-12-10 11:16:30
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void kotlinx.coroutines.internal.LockFreeLinkedListHead.addLast(kotlinx.coroutines.internal.LockFreeLinkedListNode)'
	at knot//io.ktor.events.Events.subscribe(Events.kt:24)
	at knot//io.ktor.server.engine.BaseApplicationEngine.<init>(BaseApplicationEngine.kt:49)
	at knot//io.ktor.server.engine.BaseApplicationEngine.<init>(BaseApplicationEngine.kt:30)
	at knot//io.ktor.server.cio.CIOApplicationEngine.<init>(CIOApplicationEngine.kt:27)
	at knot//io.ktor.server.cio.CIO.create(CIO.kt:16)
	at knot//io.ktor.server.cio.CIO.create(CIO.kt:12)
	at knot//io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:109)
	at knot//io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:98)
	at knot//io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:63)
	at knot//io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:38)
	at knot//io.ktor.server.engine.EmbeddedServerKt.embeddedServer$default(EmbeddedServer.kt:30)
	at knot//littlechasiu.ctm.Server.start(Server.kt:53)
	at knot//littlechasiu.ctm.TrackMap.init$lambda$3(TrackMap.kt:113)
	at knot//net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at knot//net.minecraft.server.MinecraftServer.handler$zmh000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2842)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Mac OS X (aarch64) version 15.0
	Java Version: 17.0.12, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 646207488 bytes (616 MiB) / 2010120192 bytes (1917 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 8192.00
	Virtual memory used (MB): 6493.59
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx2048M
	Fabric Mods: 
		create: Create 0.5.1-j-build.1609+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.11-4
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.8+1.20.1
			porting_lib_base: Porting Lib Base 2.3.8+1.20.1
				com_electronwill_night-config_core: core 3.6.6
				com_electronwill_night-config_toml: toml 3.6.6
				porting_lib_config: Porting Lib Config 2.3.8+1.20.1
				porting_lib_gui_utils: Porting Lib Gui Utils 2.3.8+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.8+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.8+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.8+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.8+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.8+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.8+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.8+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.8+1.20.1
				porting_lib_common: Porting Lib Common 2.3.8+1.20.1
			porting_lib_models: Porting Lib Models 2.3.8+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.8+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.8+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.8+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.8+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.8+1.20.1
				porting_lib_core: Porting Lib Core 2.3.8+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.8+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.79-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create-track-map: Create Track Map 1.4
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.13.0+kotlin.2.1.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.1.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.26.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1

### Reproduction Steps

1.
2.
3.
...

### Expected Result

just getting it to work

### Crash Report or Log

---- Minecraft Crash Report ---- // Shall we play a game?  Time: 2024-12-10 11:16:30 Description: Exception in server tick loop  java.lang.NoSuchMethodError: 'void kotlinx.coroutines.internal.LockFreeLinkedListHead.addLast(kotlinx.coroutines.internal.LockFreeLinkedListNode)' 	at knot//io.ktor.events.Events.subscribe(Events.kt:24) 	at knot//io.ktor.server.engine.BaseApplicationEngine.<init>(BaseApplicationEngine.kt:49) 	at knot//io.ktor.server.engine.BaseApplicationEngine.<init>(BaseApplicationEngine.kt:30) 	at knot//io.ktor.server.cio.CIOApplicationEngine.<init>(CIOApplicationEngine.kt:27) 	at knot//io.ktor.server.cio.CIO.create(CIO.kt:16) 	at knot//io.ktor.server.cio.CIO.create(CIO.kt:12) 	at knot//io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:109) 	at knot//io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:98) 	at knot//io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:63) 	at knot//io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:38) 	at knot//io.ktor.server.engine.EmbeddedServerKt.embeddedServer$default(EmbeddedServer.kt:30) 	at knot//littlechasiu.ctm.Server.start(Server.kt:53) 	at knot//littlechasiu.ctm.TrackMap.init$lambda$3(TrackMap.kt:113) 	at knot//net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) 	at knot//net.minecraft.server.MinecraftServer.handler$zmh000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2842) 	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) 	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) 	at java.base/java.lang.Thread.run(Unknown Source)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Mac OS X (aarch64) version 15.0 	Java Version: 17.0.12, Azul Systems, Inc. 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc. 	Memory: 646207488 bytes (616 MiB) / 2010120192 bytes (1917 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 8 	Processor Vendor: Apple Inc. 	Processor Name: Apple M1 	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0 	Microarchitecture: ARM64 SoC: Firestorm + Icestorm 	Frequency (GHz): 3.20 	Number of physical packages: 1 	Number of physical CPUs: 8 	Number of logical CPUs: 8 	Graphics card #0 name: Apple M1 	Graphics card #0 vendor: Apple (0x106b) 	Graphics card #0 VRAM (MB): 0.00 	Graphics card #0 deviceId: unknown 	Graphics card #0 versionInfo: unknown 	Memory slot #0 capacity (MB): 0.00 	Memory slot #0 clockSpeed (GHz): 0.00 	Memory slot #0 type: unknown 	Virtual memory max (MB): 8192.00 	Virtual memory used (MB): 6493.59 	Swap memory total (MB): 0.00 	Swap memory used (MB): 0.00 	JVM Flags: 1 total; -Xmx2048M 	Fabric Mods:  		create: Create 0.5.1-j-build.1609+mc1.20.1 			com_google_code_findbugs_jsr305: jsr305 3.0.2 			flywheel: Flywheel 0.6.11-4 			forgeconfigapiport: Forge Config API Port 8.0.0 			milk: Milk Lib 1.2.60 				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2 			porting_lib_accessors: Porting Lib Accessors 2.3.8+1.20.1 			porting_lib_base: Porting Lib Base 2.3.8+1.20.1 				com_electronwill_night-config_core: core 3.6.6 				com_electronwill_night-config_toml: toml 3.6.6 				porting_lib_config: Porting Lib Config 2.3.8+1.20.1 				porting_lib_gui_utils: Porting Lib Gui Utils 2.3.8+1.20.1 				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.8+1.20.1 				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.8+1.20.1 				porting_lib_utility: Porting Lib Utility 2.3.8+1.20.1 			porting_lib_brewing: Porting Lib Brewing 2.3.8+1.20.1 			porting_lib_client_events: Porting Lib Client Events 2.3.8+1.20.1 			porting_lib_entity: Porting Lib Entity 2.3.8+1.20.1 			porting_lib_extensions: Porting Lib Extensions 2.3.8+1.20.1 				porting_lib_attributes: Porting Lib Attributes 2.3.8+1.20.1 				porting_lib_common: Porting Lib Common 2.3.8+1.20.1 			porting_lib_models: Porting Lib Models 2.3.8+1.20.1 				porting_lib_fluids: Porting Lib Fluids 2.3.8+1.20.1 			porting_lib_networking: Porting Lib Networking 2.3.8+1.20.1 			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.8+1.20.1 				porting_lib_model_loader: Porting Lib Model Loader 2.3.8+1.20.1 			porting_lib_tags: Porting Lib Tags 3.0 			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.8+1.20.1 				porting_lib_core: Porting Lib Core 2.3.8+1.20.1 			porting_lib_transfer: Porting Lib Transfer 2.3.8+1.20.1 			reach-entity-attributes: Reach Entity Attributes 2.4.0 			registrate-fabric: Registrate for Fabric 1.3.79-MC1.20.1 				porting_lib_data: Porting Lib Data 2.1.1090+1.20 					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20 				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20 					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20 		create-track-map: Create Track Map 1.4 		fabric-api: Fabric API 0.92.2+1.20.1 			fabric-api-base: Fabric API Base 0.4.31+1802ada577 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577 			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577 			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577 			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77 			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577 			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377 			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377 			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577 			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577 			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577 			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577 			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677 			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577 			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577 			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777 			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577 			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577 			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577 			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377 			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577 			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577 		fabric-language-kotlin: Fabric Language Kotlin 1.13.0+kotlin.2.1.0 			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.1.0 			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.1.0 			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.1.0 			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.1.0 			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.26.1 			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0 			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0 			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1 			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.6.0 			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.6.0 			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3 			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3 			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3 		fabricloader: Fabric Loader 0.16.9 			mixinextras: MixinExtras 0.4.1 		java: OpenJDK 64-Bit Server VM 17 		minecraft: Minecraft 1.20.1 	Flywheel Backend: GL33 Instanced Arrays 	Server Running: true 	Player Count: 0 / 8; [] 	Data Packs: vanilla, fabric 	Enabled Feature Flags: minecraft:vanilla 	World Generation: Stable 	Type: Integrated Server (map_client.txt) 	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric' 	Launched Version: 1.20.1

### Operating System

mac

### CTM Version

1.4

### Create Version

0.5.1e

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Modloader Version

0.16.9

### Instance Type

Singleplayer

### Other Mods

Name
Version
Actions

Create Fabric
by tropheusj
0.5.1-j-build.1609+mc1.20.1

Create Track Map
by littlechasiu
1.4

Fabric API
by modmuss50
0.92.2+1.20.1

[Fabric Language Kotlin](tauri://localhost/project/fabric-language-kotlin/?i=create+number+2)

**Comment by Tur87** [comment]
I got the same issue on my server after updating the mods. Looks like it could be the new version of kotlin that messes it up.

**Comment by jadeiseepy** [comment]
downgrade to fkl 1.12.1+kotlin.2.0.20 or below

**Comment by Nebula434** [comment]
Duplicate of #76   
im pretty sure.
Hopefully this can get it fixed soon, this mod seems so cool 😄

**Comment by Omoli822** [comment]
It works fine on forge
